--- 
- name: Label remote cluster for ACM to deploy/remove application 
  hosts: localhost
  connection: local 
  vars:
    deployapp:  "{{ survey_deployapp }}"  # yes or no
    applabel: "prime-generator"
    ocp_username: "{{ ansible_user }}"
    ocp_password: "{{ ansible_password }}"
    ocp_api: "{{ survey_ocp_api }}"
    remote_cluster_name: "remote-aws"

  tasks:
    - block:
      - name: Authenticate to OCP 
        redhat.openshift.openshift_auth:
          username: "{{ ocp_username }}"
          password: "{{ ocp_password }}"
          host: "{{ ocp_api }}"
          validate_certs: no 
        register: openshift_auth_results

      - name: Add/Remove ACM cluster labels - {{ cluster_state }}
        kubernetes.core.k8s:
          api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
          host: "{{ ocp_api }}"
          validate_certs: false
          state: patched
          namespace: "{{ remote_cluster_name }}"
          name: "{{ remote_cluster_name }}"
          definition:
            api_version: cluster.open-cluster-management.io/v1 
            kind: ManagedCluster
            metadata: 
              labels: 
                prime-generator: "{{ cluster_state }}"

      # - name: add/remove label for remote cluster in ACM 
      #   ansible.builtin.command: "oc label  --insecure-skip-tls-verify=true --overwrite=true --token={{ openshift_auth_results.openshift_auth.api_key }} --server={{ ocp_api }} mcl/{{ remote_cluster_name }} '{{ applabel }}={{ deployapp }}'"

      always:
      - name: If login succeeded, try to log out (revoke access token)
        when: openshift_auth_results.openshift_auth.api_key is defined
        redhat.openshift.openshift_auth:
          state: absent
          api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
          host: "{{ ocp_api }}"
          validate_certs: no 

      