--- 
- name: Label remote cluster for ACM to deploy application 
  hosts: localhost
  connection: local 
  vars:
    applabel: "bookimport=yes"
    ocp_username: "{{ ansible_user }}"
    ocp_password: "{{ ansible_password }}"
    ocp_api: "{{ survey_ocp_api }}"

  tasks:
    - block:
      - name: Authenticate to OCP 
        redhat.openshift.openshift_auth:
          username: "{{ ocp_username }}"
          password: "{{ ocp_password }}"
          host: "{{ ocp_api }}"
          validate_certs: no 
        register: openshift_auth_results

      - name: add label for remote cluster in ACM 
        ansible.builtin.command: "oc label  --insecure-skip-tls-verify=true --token={{ openshift_auth_results.openshift_auth.api_key }} --server={{ ocp_api }} mcl/remotecluster '{{ applabel }}'"

      always:
      - name: If login succeeded, try to log out (revoke access token)
        when: openshift_auth_results.openshift_auth.api_key is defined
        redhat.openshift.openshift_auth:
          state: absent
          api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
          host: "{{ ocp_api }}"
          validate_certs: no 

      