- name: Get Cluster information 
  hosts: localhost
  connection: local 

  vars:
    cluster_state: "{{ survey_cluster_state }}" # Running or Hibernating
    ocp_username: "{{ ansible_user }}"
    ocp_password: "{{ ansible_password }}"
    ocp_api: "{{ survey_ocp_api }}"
    remote_cluster_name: "remote-aws"

  tasks:
    - block:
      - name: Authenticate to OCP 
        redhat.openshift.openshift_auth:
          username: "{{ ocp_username }}"
          password: "{{ ocp_password }}"
          host: "{{ ocp_api }}"
          validate_certs: no 
        register: openshift_auth_results

      - name: Set cluster state to {{ cluster_state }}
        ansible.builtin.uri:
          url: https://console-openshift-console.apps.cluster-nntsc.dynamic.redhatworkshops.io/api/proxy/plugin/mce/console/multicloud/apis/hive.openshift.io/v1/namespaces/{{ remote_cluster_name }}/clusterdeployments/{{ remote_cluster_name }}
          method: PATCH 
          body_format: json
          body: '[{op: "replace", path: "/spec/powerState", value: "{{ cluster_state }}"}]'
          headers:
            Content-Type: application/json-patch+json
            Cookie: "Authorization: Bearer {{ openshift_auth_results.openshift_auth.api_key }}"

      always:
      - name: If login succeeded, try to log out (revoke access token)
        when: openshift_auth_results.openshift_auth.api_key is defined
        redhat.openshift.openshift_auth:
          state: absent
          api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
          host: "{{ ocp_api }}"
          validate_certs: no 