- name: Get Cluster information 
  hosts: localhost
  connection: local 

  module_defaults:
    redhat.openshift.openshift_auth:
      host: "{{ survey_openshift_api }}"
      validate_certs: false # for demo env (self signed certs)

  vars:
    openshift_admin_password: "{{ ansible_user }}"
    openshift_admin_username: "{{ ansible_password }}"
    cluster_state: "{{ survey_cluster_state }}" # Running or Hibernating
    vars:
    deployapp:  "{{ survey_deployapp }}"  # yes or no
    applabel: "prime-generator"
    ocp_username: "{{ ansible_user }}"
    ocp_password: "{{ ansible_password }}"
    ocp_api: "{{ survey_ocp_api }}"
    remote_cluster_name: "remote-aws"

  tasks:
    - block:
      - name: Authenticate to OCP 
        redhat.openshift.openshift_auth:
          username: "{{ ocp_username }}"
          password: "{{ ocp_password }}"
          host: "{{ ocp_api }}"
          validate_certs: no 
        register: openshift_auth_results

      - name: Set cluster state to {{ cluster_state }}
        ansible.builtin.uri:
          url: https://console-openshift-console.apps.cluster-nntsc.dynamic.redhatworkshops.io/api/proxy/plugin/mce/console/multicloud/apis/hive.openshift.io/v1/namespaces/remote-aws/clusterdeployments/remote-aws
          method: PATCH 
          body: '[{op: "replace", path: "/spec/powerState", value: "{{ cluster_state }}"}]'
          headers:
            Authorization: Bearer {{ openshift_auth_results.openshift_auth.api_key }}