- name: Get Cluster information 
  hosts: localhost
  connection: local 

  vars:
    cluster_state: "{{ survey_cluster_state }}" # Running or Hibernating
    ocp_username: "{{ ansible_user }}"
    ocp_password: "{{ ansible_password }}"
    ocp_api: "{{ survey_ocp_api }}"
    remote_cluster_name: "remote-aws"

  tasks:
    - block:
      - name: Authenticate to OCP 
        redhat.openshift.openshift_auth:
          username: "{{ ocp_username }}"
          password: "{{ ocp_password }}"
          host: "{{ ocp_api }}"
          validate_certs: no 
        register: openshift_auth_results

      - name: Set cluster state to {{ cluster_state }}
        kubernetes.core.k8s:
          # username: "{{ ocp_username }}"
          # password: "{{ ocp_password }}"
          api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
          host: "{{ ocp_api }}"
          validate_certs: false
          state: patched
          definition:
            name: "{{ remote_cluster_name }}"
            api_version: hive.openshift.io/v1 
            kind: ClusterDeployment
            spec: 
              "Power State": "{{ cluster_state }}"

      always:
      - name: If login succeeded, try to log out (revoke access token)
        when: openshift_auth_results.openshift_auth.api_key is defined
        redhat.openshift.openshift_auth:
          state: absent
          api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
          host: "{{ ocp_api }}"
          validate_certs: no 