apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: book-import
  namespace: bookimport
  annotations:
    apps.open-cluster-management.io/deployables: ''
    apps.open-cluster-management.io/subscriptions: bookimport/book-import-subscription-1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"app.k8s.io/v1beta1","kind":"Application","metadata":{"annotations":{"apps.open-cluster-management.io/deployables":"","apps.open-cluster-management.io/subscriptions":"bookimport/book-import-subscription-1"},"name":"book-import","namespace":"bookimport"},"spec":{"componentKinds":[{"group":"apps.open-cluster-management.io","kind":"Subscription"}],"descriptor":{},"selector":{"matchExpressions":[{"key":"app","operator":"In","values":["book-import"]}]}}}
    open-cluster-management.io/user-group: c3lzdGVtOnNlcnZpY2VhY2NvdW50cyxzeXN0ZW06c2VydmljZWFjY291bnRzOm9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50LHN5c3RlbTphdXRoZW50aWNhdGVk
    open-cluster-management.io/user-identity: c3lzdGVtOnNlcnZpY2VhY2NvdW50Om9wZW4tY2x1c3Rlci1tYW5hZ2VtZW50Om11bHRpY2x1c3Rlci1hcHBsaWNhdGlvbnM=
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - book-import
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: book-import-subscription-1
  namespace: bookimport
  annotations:
    apps.open-cluster-management.io/git-branch: master-no-pre-post
    apps.open-cluster-management.io/git-path: book-import
    apps.open-cluster-management.io/manual-refresh-time: '2024-03-04T17:55:45.759Z'
    apps.open-cluster-management.io/reconcile-option: merge
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.open-cluster-management.io/v1","kind":"Subscription","metadata":{"annotations":{"apps.open-cluster-management.io/git-branch":"master-no-pre-post","apps.open-cluster-management.io/git-path":"book-import","apps.open-cluster-management.io/reconcile-option":"merge"},"labels":{"app":"book-import","app.kubernetes.io/part-of":"book-import","apps.open-cluster-management.io/reconcile-rate":"medium"},"name":"book-import-subscription-1","namespace":"bookimport"},"posthooks":{},"prehooks":{},"spec":{"channel":"nsgithubcom-hichammourad-book-impor-ns/nsgithubcom-hichammourad-book-impor","placement":{"placementRef":{"kind":"Placement","name":"book-import-placement-1"}}}}
    open-cluster-management.io/user-group: c3lzdGVtOmF1dGhlbnRpY2F0ZWQ6b2F1dGgsc3lzdGVtOmF1dGhlbnRpY2F0ZWQ=
    open-cluster-management.io/user-identity: YWRtaW4=
  labels:
    app: book-import
    app.kubernetes.io/part-of: book-import
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: nsgithubcom-hichammourad-book-impor-ns/nsgithubcom-hichammourad-book-impor
  placement:
    placementRef:
      name: book-import-placement-3
      kind: Placement
posthooks: {}
prehooks: {}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: book-import-placement-3
  namespace: bookimport
  labels:
    app: book-import
  selfLink:
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: bookimport
              operator: In
              values:
                - 'yes'
  clusterSets:
    - remote
    - local
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: remote
  namespace: bookimport
spec:
  clusterSet: remote
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: local
  namespace: bookimport
spec:
  clusterSet: local
