---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-usage
  namespace: openshift-monitoring
spec:
  groups:
    - name: example_alerts
      rules:
      - alert: HostHighCpuLoad
        expr: cluster:node_cpu:ratio_rate5m{cluster=""} > .20
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Host high CPU load (instance {{ $labels.instance }})"
          description: "CPU load is > 20%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
