---
- name: OCP Cluster Scaling with AlertManager
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
        data_host_path: ""
  rules:
    - name: Awaken Hibernated Cluster
      condition: 
        all: 
          - event.alert.labels.alertname == 'HostHighCpuLoad' 
          - event.alert.status == 'firing' 
      actions:
        - set_fact:
            fact:
              lastAwake: event.alert.startsAt
        - run_job_template:
            name: "[ACM] Wake/Hibernate Remote Cluster"
            organization: Demo 
            job_args:
              extra_vars:
                survey_ocp_api: https://api.cluster-nntsc.dynamic.redhatworkshops.io:6443
                survey_cluster_state: Running
          # delay: 7200 # seconds, this is 2 hours

    - name: Hibernate Cluster
      condition: 
        all: 
          - event.alert.labels.alertname == 'HostHighCpuLoad' 
          - event.alert.status == 'resolved'
#           - ((event.alert.startsAt | to_datetime).total_seconds() - facts.lastAwake) > 7200   
      action:
        run_job_template:
          name: "[ACM] Wake/Hibernate Remote Cluster"
          organization: Demo 
          job_args:
            extra_vars:
              survey_ocp_api: https://api.cluster-nntsc.dynamic.redhatworkshops.io:6443
              survey_cluster_state: Hibernating


