---
- name: AlertManager Example 
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
        data_host_path: ""
  rules:
    - name: Run Job Template (test)
      condition: event.alert.labels.alertname == "HostHighCpuLoad"
      action:
        debug:
      #   run_job_template:
      #     name: Demo Job Template
      # delay: 7200 # seconds, this is 2 hours

