---
- name: AlertManager Example 
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Print Event
      condition: event.payload is defined
      action:
        debug:

