---
- name: AlertManager Example 
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
        data_host_path: ""
  rules:
    - name: Print Event
      condition: event.labels.alertname == "HostHighCpuLoad" and event.alert.status == "firing"
      action:
        debug:

