---
- name: AlertManager Example 
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 33710
        data_host_path: ""
  rules:
    - name: Print Event
      condition: event.alert is defined
      action:
        debug:

