---
- name: AlertManager Example 
  hosts: localhost
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: alertmanager-main-openshift-monitoring.apps.acmhub.dinesh154.dfw.ocp.run/api
        port: 9097
  rules:
    - name: Print Event
      condition: 1=1
      action:
        debug:

